### ISSUE TITLE
nefunkcne pre windows

### ISSUE THREAD

**Issue by xzelenakm1** [ainthek/node-boilerplate#2]
postup nie je funkcny pre windows z 2 dovodov:

1. nespravne nasetovanie do premennych
2. nepozna prikaz "sed"

**Comment by ainthek** [comment]
bad joke ? install git 2.0 as instructed with bash console ;-(((

**Comment by xzelenakm1** [comment]
Ospravedlnujem sa, dnes to uz funguje, ale vcera to neslo :( pritom som to
robil cez original bash konzolu. Aj s Jakubom sme na to pozerali a cudovali
sme sa, tak mi poradil, ze tam mam otvorit issue. Dnes vsak ta konzola
vyzera o nieco inac ako vcera, posielam v prilohe screenshot (vlavo -
otvorena dnes, vpravo - otvorena vcera). Sorry este raz za zbytocne zmatky.
Pekny den,

Matus

ut 25. 9. 2018 o 0:53 Ainthe Kitchen <notifications@github.com> napísal(a):
